style: try make code more consistent and align HTML DSL to 4 spaces indentation
fsprojects/FSharp.Formatting pull request #948
Opened 2024-12-30 20:18 UTC by MangelMaxime

Like requested in #932 this is a PR dedicated to the Fantomas configuration.

When working on a new structure for the API documentation, I discovered that the current setup make it difficult to work with the HTML dsl.

Indeed, the elements inside of the list of the DSL are not naturally aligned to the standard 4 spaces indentations so you often need to manually place the code by adding 1, 2, 3 spaces, etc.

The important rules are to avoid the indentation issue are:

```editorconfig
fsharp_experimental_elmish = true
fsharp_array_or_list_multiline_formatter = number_of_items
fsharp_max_array_or_list_number_of_items = 0
fsharp_multi_line_lambda_closing_newline = true
fsharp_multiline_bracket_style = aligned
```

The rest of the rules are here to enforce more consistency overall but are probably more subject to debate. I just wanted to take this opportunity of updating the Fantomas config to open the discussion.

For this PR, applied the new rules to `GenerateHtml.fs` only but we could and perhaps should apply them to all the files for consistency ?

2025-01-02 07:07 UTC, nojaf requested changes
I'd like a subset of these changes that focus on the DSL.
Otherwise it is just very inconsistent toward the rest of the codebase.

2025-01-02 07:07 UTC, nojaf commented on .editorconfig
> +fsharp_max_array_or_list_number_of_items = 0
I don't really like this one, it makes too many single item list format in three lines. Makes it all rather excessive.

2025-01-02 07:07 UTC, nojaf commented on .editorconfig
> +fsharp_align_function_signature_to_indentation = true
I'm not seeing the effects from this in this file.

2025-01-02 07:07 UTC, nojaf commented on .editorconfig
> +fsharp_max_if_then_else_short_width = 0
I don't think this really solves any problem.

2025-01-02 07:07 UTC, nojaf commented on .editorconfig
> +fsharp_max_record_number_of_items = 0
I don't think this really solves any problem.

2025-01-02 07:07 UTC, nojaf commented on .editorconfig
> +fsharp_alternative_long_member_definitions = true
Not sure if used.

2025-01-02 10:06 UTC, MangelMaxime commented on .editorconfig
> +fsharp_max_if_then_else_short_width = 0
This solves consistency in formatting:

![CleanShot 2025-01-02 at 11 04 30@2x](https://github.com/user-attachments/assets/7adc46b3-23b9-47b3-ac0a-1d7bc0e73982)

Personally, I value having a single way of reading the code compared to have sometimes something take 1 lines, sometimes 2 or more.

Can disable if still wanted

2025-01-02 10:10 UTC, MangelMaxime commented on .editorconfig
> +fsharp_align_function_signature_to_indentation = true
`fsharp_multiline_bracket_style = aligned` is need to ensure the code inside of the DSL is aligned to the 4 spaces guides

![CleanShot 2025-01-02 at 11 09 38@2x](https://github.com/user-attachments/assets/17194b9d-29b9-44e7-885e-99a9310d9ffe)

`fsharp_keep_max_number_of_blank_lines = 1` has effet on code like that:

![CleanShot 2025-01-02 at 11 08 12@2x](https://github.com/user-attachments/assets/774162de-3e9b-4f5f-9731-7b9a8bc7c1f4)


`fsharp_align_function_signature_to_indentation = true` does nothing indeed, probably a left over copy/paste from experimentation/my own configuration. Will remove it

2025-01-02 10:13 UTC, MangelMaxime commented on .editorconfig
> +fsharp_max_array_or_list_number_of_items = 0
This makes the code more consistent it always align to the 4 spaces guides and avoid having to reformat the list over and over when adding a new element:

![CleanShot 2025-01-02 at 11 10 52@2x](https://github.com/user-attachments/assets/d36a7c11-1834-4d0f-814a-d568de9c076d)

For example, if I want to add a new element to `embed` with that configuration I can simply press `Enter` and be ready with it. Without I, need to move the list, align it, split the inner value on multiple lines, etc. Or add `;` to add the new item but if it is too long I need to go back manually placing stuff around.

2025-01-02 10:14 UTC, MangelMaxime commented on .editorconfig
> +fsharp_max_record_number_of_items = 0
Indeed, it does nothing in this file because it doesn't have any Record.

In the general concept, it is once again for consistency all record are formatted the same way thanks to that configuration. But will remove it.

2025-01-02 10:14 UTC, MangelMaxime commented on .editorconfig
> +fsharp_alternative_long_member_definitions = true
Does nothing in this file

2025-01-02 10:16 UTC, MangelMaxime commented
@nojaf Thanks for the review, I made a first pass to remove the rules which had no effect in this file.

Waiting for feedback on the rest, as I explained why the rule exist or not. Will adapt the PR accordingly :)

2025-01-02 10:26 UTC, nojaf requested changes

2025-01-02 10:26 UTC, nojaf commented on .editorconfig
> -
Please don't remove `[*.{fs,fsi,fsx}]`, honestly rule of thumb change as little as possible.

2025-01-02 10:26 UTC, nojaf commented on .editorconfig
> +fsharp_max_array_or_list_number_of_items = 0
pressing `;` and formatting isn't the end of the world.
How many times are really facing this issue? If you had this once I really don't feel like this is worth it. If you have this 20 times in an hour I could kinda get it, but even then...

2025-01-02 10:26 UTC, nojaf commented on .editorconfig
> +fsharp_max_if_then_else_short_width = 0
Please remove

2025-01-02 19:17 UTC, MangelMaxime commented on .editorconfig
> -
These settings make sense for all the files but ok

2025-01-02 19:17 UTC, MangelMaxime commented on .editorconfig
> +fsharp_max_array_or_list_number_of_items = 0
More often than I want to have to deal with it 🙂

2025-01-02 19:17 UTC, MangelMaxime commented on .editorconfig
> +fsharp_max_array_or_list_number_of_items = 0
Removing this code also make it harder to read some line IHMO.

![CleanShot 2025-01-02 at 20 14 26@2x](https://github.com/user-attachments/assets/639ec8b3-51f8-4d73-a8f4-2d034b9de4b4)

I removed it but we can re-introduce if wanted before merging.

2025-01-02 19:18 UTC, MangelMaxime commented
@nojaf I think I made all the changes requested.

Last ones that could change perhaps are:

- https://github.com/fsprojects/FSharp.Formatting/pull/948#discussion_r1901185473
- https://github.com/fsprojects/FSharp.Formatting/pull/948#discussion_r1901182270

If no more changes required this PR should be ready.

2025-01-03 07:22 UTC, nojaf approved these changes
Thanks!

2025-01-03 07:22 UTC, merged